# Generated by Django 3.2 on 2021-04-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='receiver_name',
            field=models.CharField(max_length=100),
        ),
    ]
